export * from "./colors";
export * from "./numbers";
export * from "./sizes";
import { sizes } from "./sizes";
import { colors } from "./colors";
import { numbers } from "./numbers";
import { TCommonProps, TDefaultTheme, TSizeProps } from "./types";

/**
 * Common properties for the theme.
 */
export const commonProps: TCommonProps = {
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset",
};

/**
 * Size properties for the theme.
 */
export const sizeProps: TSizeProps = {
  ...commonProps,
  fitContent: "fit-content",
  maxContent: "max-content",
  minContent: "min-content",
  webkitFillAvailable: "-webkit-fill-available",
  mozAvailable: "-moz-available",
  ...sizes,
};

/**
 * Default theme object.
 */
export const defaultTheme: TDefaultTheme = {
  linearColor: Object.assign({}, colors),
  colorInterpolation: Object.assign({}, colors),
  colorRendering: Object.assign({}, colors),
  textFillColor: Object.assign({}, colors),
  marginLeft: Object.assign({}, sizeProps),
  marginRight: Object.assign({}, sizeProps),
  marginTop: Object.assign({}, sizeProps),
  marginBottom: Object.assign({}, sizeProps),
  paddingLeft: Object.assign({}, sizeProps),
  paddingRight: Object.assign({}, sizeProps),
  paddingTop: Object.assign({}, sizeProps),
  paddingBottom: Object.assign({}, sizeProps),
  background: Object.assign({}, colors),
  fontColor: Object.assign({}, colors),
  backgroundColor: Object.assign({}, colors),
  padding: Object.assign({}, sizeProps),
  margin: Object.assign({}, sizeProps),
  left: Object.assign({}, sizeProps),
  right: Object.assign({}, sizeProps),
  top: Object.assign({}, sizeProps),
  bottom: Object.assign({}, sizeProps),
  color: Object.assign({}, colors),
  mx: Object.assign({}, sizeProps),
  my: Object.assign({}, sizeProps),
  px: Object.assign({}, sizeProps),
  py: Object.assign({}, sizeProps),
  pb: Object.assign({}, sizeProps),
  pr: Object.assign({}, sizeProps),
  mb: Object.assign({}, sizeProps),
  pl: Object.assign({}, sizeProps),
  mr: Object.assign({}, sizeProps),
  ml: Object.assign({}, sizeProps),
  pt: Object.assign({}, sizeProps),
  mt: Object.assign({}, sizeProps),
  bg: Object.assign({}, colors),
  p: Object.assign({}, sizeProps),
  m: Object.assign({}, sizeProps),
  minW: Object.assign({}, sizeProps),
  minH: Object.assign({}, sizeProps),
  maxHeight: Object.assign({}, sizeProps),
  maxWidth: Object.assign({}, sizeProps),
  minHeight: Object.assign({}, sizeProps),
  minWidth: Object.assign({}, sizeProps),
  maxH: Object.assign({}, sizeProps),
  maxW: Object.assign({}, sizeProps),
  placeHolderColor: Object.assign({}, colors),
  borderColor: Object.assign({}, colors),
  textDecorationColor: Object.assign({}, colors),
  textEmphasisColor: Object.assign({}, colors),
  borderRadius: {
    ...commonProps,
    ...sizes,
  },
  gap: {
    ...commonProps,
    ...sizes,
  },
  scrollbarColor: {
    ...commonProps,
    ...colors,
  },
  boxSizing: {
    ...commonProps,
    borderBox: "border-box",
    contentBox: "content-box",
  },
  scrollbarWidth: {
    ...commonProps,
    auto: "auto",
    thin: "thin",
    none: "none",
    revertLayer: "revert-layer",
  },
  objectFit: {
    ...commonProps,
    none: "none",
    contain: "contain",
    cover: "cover",
    fill: "fill",
    scaleDown: "scale-down",
  },
  position: {
    ...commonProps,
    absolute: "absolute",
    fixed: "fixed",
    relative: "relative",
    static: "static",
    sticky: "sticky",
  },
  flexDirection: {
    ...commonProps,
    row: "row",
    rowReverse: "row-reverse",
    column: "column",
    columnReverse: "column-reverse",
  },
  width: {
    ...commonProps,
    fitContent: "fit-content",
    maxContent: "max-content",
    minContent: "min-content",
    webkitFillAvailable: "-webkit-fill-available",
    mozAvailable: "-moz-available",
    optimizedWidth: `-moz-available;width: -webkit-fill-available`,
    ...sizes,
  },
  height: {
    ...commonProps,
    fitContent: "fit-content",
    maxContent: "max-content",
    minContent: "min-content",
    webkitFillAvailable: "-webkit-fill-available",
    mozAvailable: "-moz-available",
    optimizedHeight: `-moz-available;height: -webkit-fill-available`,
    ...sizes,
  },
  textIndent: {
    ...sizeProps,
    revertLayer: "revert-layer",
  },
  display: {
    ...commonProps,
    block: "block",
    contents: "contents",
    flex: "flex",
    flowRoot: "flow-root",
    grid: "grid",
    inline: "inline",
    inlineBlock: "inline-block",
    inlineFlex: "inline-flex",
    inlineGrid: "inline-grid",
    inlineTable: "inline-table",
    listItem: "list-item",
    none: "none",
    table: "table",
    tableCaption: "table-caption",
    tableCell: "table-cell",
    tableColumn: "table-column",
    tableColumnGroup: "table-column-group",
    tableFooterGroup: "table-footer-group",
    tableHeaderGroup: "table-header-group",
    tableRow: "table-row",
    tableRowGroup: "table-row-group",
    webkitBox: "-webkit-box",
    webkitInlineBox: "-webkit-inline-box",
  },
  fontSize: {
    ...sizeProps,
    large: "large",
    medium: "medium",
    small: "small",
    smaller: "smaller",
    xLarge: "x-large",
    xSmall: "x-small",
    xxLarge: "xx-large",
    xxSmall: "xx-small",
    xxxLarge: "xxx-large",
    webkitXxxLarge: "-webkit-xxx-large",
  },
  fontWeight: {
    ...sizeProps,
    "100": "100",
    "200": "200",
    "300": "300",
    "400": "400",
    "500": "500",
    "600": "600",
    "700": "700",
    "800": "800",
    "900": "900",
    bold: "bold",
    bolder: "bolder",
    lighter: "lighter",
    normal: "normal",
  },
  textAlign: {
    ...commonProps,
    center: "center",
    end: "end",
    justify: "justify",
    left: "left",
    right: "right",
    start: "start",
    webkitAuto: "-webkit-auto",
    webkitCenter: "-webkit-center",
    webkitLeft: "-webkit-left",
    webkitMatchParent: "-webkit-match-parent",
    webkitRight: "-webkit-right",
  },
  flexShrink: {
    ...commonProps,
    revertLayer: "revert-layer",
  },
  zIndex: {
    ...commonProps,
    auto: "auto",
    ...numbers,
  },
  fontStyle: {
    ...commonProps,
    italic: "italic",
    normal: "normal",
    oblique: "oblique",
  },
  alignContent: {
    ...commonProps,
    baseline: "baseline",
    center: "center",
    end: "end",
    flexEnd: "flex-end",
    flexStart: "flex-start",
    normal: "normal",
    spaceAround: "space-around",
    spaceBetween: "space-between",
    spaceEvenly: "space-evenly",
    start: "start",
    stretch: "stretch",
  },
  alignItems: {
    ...commonProps,
    baseline: "baseline",
    center: "center",
    end: "end",
    flexEnd: "flex-end",
    flexStart: "flex-start",
    normal: "normal",
    selfEnd: "self-end",
    selfStart: "self-start",
    start: "start",
    stretch: "stretch",
  },
  overflowY: {
    ...commonProps,
    auto: "auto",
    clip: "clip",
    hidden: "hidden",
    revertLayer: "revertLayer",
    scroll: "scroll",
    visible: "visible",
  },
  overflowX: {
    ...commonProps,
    auto: "auto",
    clip: "clip",
    hidden: "hidden",
    revertLayer: "revertLayer",
    scroll: "scroll",
    visible: "visible",
  },
  overflow: {
    ...commonProps,
    auto: "auto",
    clip: "clip",
    hidden: "hidden",
    revertLayer: "revertLayer",
    scroll: "scroll",
    visible: "visible",
  },
  flexWrap: {
    ...commonProps,
    noWrap: "nowrap",
    wrap: "wrap",
    wrapReverse: "wrap-reverse",
  },
  gridTemplateColumns: {
    ...commonProps,
    auto: "auto",
    maxContent: "max-content",
    minContent: "min-content",
    none: "none",
  },
  gridTemplateRows: {
    ...commonProps,
    auto: "auto",
    maxContent: "max-content",
    minContent: "min-content",
    none: "none",
  },
  cursor: {
    ...commonProps,
    alias: "alias",
    allScroll: "all-scroll",
    auto: "auto",
    cell: "cell",
    colResize: "col-resize",
    contextMenu: "context-menu",
    copy: "copy",
    crosshair: "crosshair",
    default: "default",
    eResize: "e-resize",
    ewResize: "ew-resize",
    grab: "grab",
    grabbing: "grabbing",
    help: "help",
    move: "move",
    nResize: "n-resize",
    neResize: "ne-resize",
    neswResize: "nesw-resize",
    noDrop: "no-drop",
    none: "none",
    notAllowed: "not-allowed",
    nsResize: "ns-resize",
    nwResize: "nw-resize",
    nwseResize: "nwse-resize",
    pointer: "pointer",
    progress: "progress",
    rowResize: "row-resize",
    sResize: "s-resize",
    seResize: "se-resize",
    swResize: "sw-resize",
    text: "text",
    verticalText: "vertical-text",
    wResize: "w-resize",
    wait: "wait",
    zoomIn: "zoom-in",
    zoomOut: "zoom-out",
    webkitGrab: "-webkit-grab",
    webkitGrabbing: "-webkit-grabbing",
    webkitZoomIn: "-webkit-zoom-in",
    webkitZoomOut: "-webkit-zoom-out",
  },
  alignSelf: {
    ...commonProps,
    auto: "auto",
    baseline: "baseline",
    center: "center",
    end: "end",
    flexEnd: "flex-end",
    flexStart: "flex-start",
    normal: "normal",
    selfEnd: "self-end",
    selfStart: "self-start",
    start: "start",
    stretch: "stretch",
  },
  textWrap: {
    ...commonProps,
    balance: "balance",
    noWrap: "nowrap",
    pretty: "pretty",
    wrap: "wrap",
  },
  justifyContent: {
    ...commonProps,
    center: "center",
    end: "end",
    flexEnd: "flex-end",
    flexStart: "flex-start",
    left: "left",
    normal: "normal",
    right: "right",
    spaceAround: "space-around",
    spaceBetween: "space-between",
    spaceEvenly: "space-evenly",
    start: "start",
    stretch: "stretch",
  },
  textTransform: {
    ...commonProps,
    capitalize: "capitalize",
    lowercase: "lowercase",
    mathAuto: "math-auto",
    none: "none",
    upset: "unset",
    uppercase: "uppercase",
  },
  objectPosition: {
    ...commonProps,
    bottom: "bottom",
    center: "center",
    left: "left",
    right: "right",
    top: "top",
  },
  textDecorationStyle: {
    ...commonProps,
    solid: "solid",
    double: "double",
    dotted: "dotted",
    dashed: "dashed",
    wavy: "wavy",
  },
  textUnderlineOffset: {
    ...commonProps,
    auto: "auto",
  },
  textEmphasis: {
    ...commonProps,
    none: "none",
    accent: "accent",
    dot: "dot",
    circle: "circle",
    disc: "disc",
  },
  borderImageOutset: {
    ...commonProps,
  },
  borderImageRepeat: {
    ...commonProps,
    stretch: "stretch",
    repeat: "repeat",
    round: "round",
    space: "space",
  },
  borderImageSlice: {
    ...commonProps,
  },
  borderImageSource: {
    ...commonProps,
  },
  borderImageWidth: {
    ...commonProps,
    auto: "auto",
  },
  borderBlock: {
    ...commonProps,
    start: "start",
    end: "end",
  },
  textDecorationLine: {
    ...commonProps,
    lineThrough: "line-through",
    overline: "overline",
    underline: "underline",
    blink: "blink",
  },
  transformStyle: {
    ...commonProps,
    flat: "flat",
    preserve3d: "preserve-3d",
  },
  justifyItems: {
    ...commonProps,
    auto: "auto",
    baseline: "baseline",
    center: "center",
    end: "end",
    start: "start",
    stretch: "stretch",
  },
  whiteSpace: {
    ...commonProps,
    breakSpaces: "break-spaces",
    normal: "normal",
    nowrap: "nowrap",
    pre: "pre",
    preLine: "pre-line",
    preWrap: "pre-wrap",
    revertLayer: "revert-layer",
    mozPreSpace: "-moz-pre-space",
  },
  lineHeight: {
    ...commonProps,
    normal: "normal",
    revertLayer: "revert-layer",
    mozBlockHeight: "-moz-block-height",
    ...sizes,
  },
  textRendering: {
    ...commonProps,
    auto: "auto",
    geometricPrecision: "geometricprecision",
    optimizeLegibility: "optimizelegibility",
    optimizeSpeed: "optimizespeed",
    revertLayer: "revert-layer",
  },
  textDecoration: {
    auto: "auto",
    blink: "blink",
    dashed: "dashed",
    double: "double",
    lineThrough: "line-through",
    none: "none",
    overline: "overline",
    solid: "solid",
    underline: "underline",
    wavy: "wavy",
    revertLayer: "revert-layer",
    ...commonProps,
  },
  transition: Object.assign({}, commonProps),
  opacity: Object.assign({}, commonProps),
  backgroundClipText: Object.assign({}, commonProps),
  boxShadow: Object.assign({}, commonProps),
  backgroundTranslucent: Object.assign({}, commonProps),
  filter: Object.assign({}, commonProps),
  bTopRadius: Object.assign({}, commonProps),
  bBottomRadius: Object.assign({}, commonProps),
  bRadius: Object.assign({}, commonProps),
  bLeftRadius: Object.assign({}, commonProps),
  bRightRadius: Object.assign({}, commonProps),
  bRadiusTop: Object.assign({}, commonProps),
  bRadiusBottom: Object.assign({}, commonProps),
  bRadiusLeft: Object.assign({}, commonProps),
  bRadiusRight: Object.assign({}, commonProps),
  bRadiusTopLeft: Object.assign({}, commonProps),
  bRadiusTopRight: Object.assign({}, commonProps),
  bRadiusBottomLeft: Object.assign({}, commonProps),
  bRadiusBottomRight: Object.assign({}, commonProps),
  flexGrow: Object.assign({}, commonProps),
  gridColumnGap: Object.assign({}, commonProps),
  gridRowGap: Object.assign({}, commonProps),
  gridGap: Object.assign({}, commonProps),
  gridAutoFlow: Object.assign({}, commonProps),
  gridAutoColumns: Object.assign({}, commonProps),
  gridAutoRows: Object.assign({}, commonProps),
  gridColumnStart: Object.assign({}, commonProps),
  gridColumnEnd: Object.assign({}, commonProps),
  gridRowStart: Object.assign({}, commonProps),
  gridRowEnd: Object.assign({}, commonProps),
  gridRow: Object.assign({}, commonProps),
  gridColumn: Object.assign({}, commonProps),
  gridColumnStartEnd: Object.assign({}, commonProps),
  gridRowStartEnd: Object.assign({}, commonProps),
  justifySelf: Object.assign({}, commonProps),
  placeItems: Object.assign({}, commonProps),
  placeContent: Object.assign({}, commonProps),
  placeSelf: Object.assign({}, commonProps),
  userDrag: Object.assign({}, commonProps),
  userResize: Object.assign({}, commonProps),
  transitionProperty: Object.assign({}, commonProps),
  transitionDuration: Object.assign({}, commonProps),
  transitionTimingFunction: Object.assign({}, commonProps),
  transitionDelay: Object.assign({}, commonProps),
  animation: Object.assign({}, commonProps),
  transform: Object.assign({}, commonProps),
  transformOrigin: Object.assign({}, commonProps),
  perspective: Object.assign({}, commonProps),
  perspectiveOrigin: Object.assign({}, commonProps),
  backfaceVisibility: Object.assign({}, commonProps),
  willChange: Object.assign({}, commonProps),
  letterSpacing: Object.assign({}, commonProps),
  wordSpacing: Object.assign({}, commonProps),
  textOverflow: {
    ellipsis: "ellipsis",
    clip: "clip",
    revertLayer: "revert-layer",
    ...commonProps,
  },
  columnCount: Object.assign({}, commonProps),
  columnGap: Object.assign({}, commonProps),
  columnRule: Object.assign({}, commonProps),
  columnWidth: Object.assign({}, commonProps),
  scrollSnapType: Object.assign({}, commonProps),
  scrollBehavior: Object.assign({}, commonProps),
  scrollSnapAlign: Object.assign({}, commonProps),
  animationDelay: Object.assign({}, commonProps),
  animationDirection: Object.assign({}, commonProps),
  animationDuration: Object.assign({}, commonProps),
  animationFillMode: Object.assign({}, commonProps),
  animationIterationCount: Object.assign({}, commonProps),
  animationName: Object.assign({}, commonProps),
  animationPlayState: Object.assign({}, commonProps),
  animationTimingFunction: Object.assign({}, commonProps),
  boxShadowInset: Object.assign({}, commonProps),
  userFocus: Object.assign({}, commonProps),
  userSelectText: Object.assign({}, commonProps),
  userSelectNone: Object.assign({}, commonProps),
  userSelectAll: Object.assign({}, commonProps),
  userSelectAuto: Object.assign({}, commonProps),
  mixBlendMode: Object.assign({}, commonProps),
  clipPath: Object.assign({}, commonProps),
  backdropFilter: Object.assign({}, commonProps),
  backdropBlur: Object.assign({}, commonProps),
  backdropBrightness: Object.assign({}, commonProps),
  backdropContrast: Object.assign({}, commonProps),
  backdropGrayscale: Object.assign({}, commonProps),
  backdropHueRotate: Object.assign({}, commonProps),
  backdropInvert: Object.assign({}, commonProps),
  backdropOpacity: Object.assign({}, commonProps),
  backdropSaturate: Object.assign({}, commonProps),
  backdropSepia: Object.assign({}, commonProps),
  backdropDropShadow: Object.assign({}, commonProps),
  borderImage: Object.assign({}, commonProps),
  textEmphasisStyle: Object.assign({}, commonProps),
  textEmphasisPosition: Object.assign({}, commonProps),
  scrollSnapPointsX: Object.assign({}, commonProps),
  scrollSnapPointsY: Object.assign({}, commonProps),
  columnSpan: Object.assign({}, commonProps),
  hyphens: Object.assign({}, commonProps),
  textAlignLast: Object.assign({}, commonProps),
  textJustify: Object.assign({}, commonProps),
  fontVariant: Object.assign({}, commonProps),
  fontFeatureSettings: Object.assign({}, commonProps),
  wordBreak: Object.assign({}, commonProps),
  wordWrap: Object.assign({}, commonProps),
  overscrollBehavior: Object.assign({}, commonProps),
  overscrollBehaviorX: Object.assign({}, commonProps),
  overscrollBehaviorY: Object.assign({}, commonProps),
  clipRule: Object.assign({}, commonProps),
  fillRule: Object.assign({}, commonProps),
  isolation: Object.assign({}, commonProps),
  pointerEvents: {
    ...commonProps,
    all: "all",
    auto: "auto",
    boundingBox: "bounding-box",
    fill: "fill",
    none: "none",
    painted: "painted",
    stroke: "stroke",
    visible: "visible",
    visibleFill: "visiblefill",
    visiblePainted: "visiblepainted",
    visibleStroke: "visiblestroke",
  },
  resize: Object.assign({}, commonProps),
  shapeOutside: Object.assign({}, commonProps),
  listStyleType: Object.assign({}, commonProps),
  listStylePosition: Object.assign({}, commonProps),
  listStyleImage: Object.assign({}, commonProps),
  userZoom: Object.assign({}, commonProps),
  maxLines: Object.assign({}, commonProps),
  textDecorationSkipInk: Object.assign({}, commonProps),
  transitionTiming: Object.assign({}, commonProps),
  transitionDurationTiming: Object.assign({}, commonProps),
  scrollMargin: Object.assign({}, commonProps),
  scrollMarginBlock: Object.assign({}, commonProps),
  scrollMarginBlockStart: Object.assign({}, commonProps),
  scrollMarginBlockEnd: Object.assign({}, commonProps),
  scrollMarginInline: Object.assign({}, commonProps),
  scrollMarginInlineStart: Object.assign({}, commonProps),
  scrollMarginInlineEnd: Object.assign({}, commonProps),
  maskImage: Object.assign({}, commonProps),
  maskSize: Object.assign({}, commonProps),
  maskRepeat: Object.assign({}, commonProps),
  maskPosition: Object.assign({}, commonProps),
  maskClip: Object.assign({}, commonProps),
  maskOrigin: Object.assign({}, commonProps),
  maskComposite: Object.assign({}, commonProps),
  maskType: Object.assign({}, commonProps),
  maskBorder: Object.assign({}, commonProps),
  maskBorderOutset: Object.assign({}, commonProps),
  maskBorderRepeat: Object.assign({}, commonProps),
  maskBorderSlice: Object.assign({}, commonProps),
  maskBorderSource: Object.assign({}, commonProps),
  maskBorderWidth: Object.assign({}, commonProps),
  maskBorderRepeatX: Object.assign({}, commonProps),
  maskBorderRepeatY: Object.assign({}, commonProps),
  scrollSnapStop: Object.assign({}, commonProps),
  scrollSnapAlignY: Object.assign({}, commonProps),
  scrollSnapAlignX: Object.assign({}, commonProps),
  scrollSnapStopX: Object.assign({}, commonProps),
  scrollSnapStopY: Object.assign({}, commonProps),
  boxShadowX: Object.assign({}, commonProps),
  boxShadowY: Object.assign({}, commonProps),
  backdropBlendMode: Object.assign({}, commonProps),
  backdropDropShadowX: Object.assign({}, commonProps),
  backdropDropShadowY: Object.assign({}, commonProps),
  backdropDropShadowBlur: Object.assign({}, commonProps),
  backdropDropShadowSpread: Object.assign({}, commonProps),
  gridAutoRowsMin: Object.assign({}, commonProps),
  gridAutoRowsMax: Object.assign({}, commonProps),
  gridAutoColumnsMin: Object.assign({}, commonProps),
  gridAutoColumnsMax: Object.assign({}, commonProps),
  gridColumnStartMin: Object.assign({}, commonProps),
  gridColumnStartMax: Object.assign({}, commonProps),
  gridColumnEndMin: Object.assign({}, commonProps),
  gridColumnEndMax: Object.assign({}, commonProps),
  gridRowStartMin: Object.assign({}, commonProps),
  gridRowStartMax: Object.assign({}, commonProps),
  gridRowEndMin: Object.assign({}, commonProps),
  gridRowEndMax: Object.assign({}, commonProps),
  shapeMargin: Object.assign({}, commonProps),
  shapeImageThreshold: Object.assign({}, commonProps),
  filterBlur: Object.assign({}, commonProps),
  filterBrightness: Object.assign({}, commonProps),
  filterContrast: Object.assign({}, commonProps),
  filterGrayscale: Object.assign({}, commonProps),
  filterHueRotate: Object.assign({}, commonProps),
  filterInvert: Object.assign({}, commonProps),
  filterOpacity: Object.assign({}, commonProps),
  filterSaturate: Object.assign({}, commonProps),
  filterSepia: Object.assign({}, commonProps),
  filterDropShadow: Object.assign({}, commonProps),
  willChangeProperty: Object.assign({}, commonProps),
  backgroundClip: Object.assign({}, commonProps),
  imageRendering: Object.assign({}, commonProps),
  shapeRendering: Object.assign({}, commonProps),
  userSelect: {
    all: "all",
    auto: "auto",
    none: "none",
    text: "text",
    contain: "contain",
    revertLayer: "revert-layer",
    ...commonProps,
  },
  border: Object.assign({}, commonProps),
  textShadow: Object.assign({}, commonProps),
};
