import { TCommonProps, TDefaultTheme, TSizeProps } from "./types";
import { Numbers } from "@/numbers";
import { colors } from "./colors";
import { sizes } from "@/sizes";
export * from "./colors";
export * from "./types";
/**
 * Common properties for the theme.

 *  */
export const commonProps: TCommonProps = {
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset",
};

/**
 * Size properties for the theme.

 *  */
export const sizeProps: TSizeProps = {
  ...commonProps,
  fitContent: "fit-content",
  maxContent: "max-content",
  minContent: "min-content",
  webkitFillAvailable: "-webkit-fill-available",
  mozAvailable: "-moz-available",
  ...sizes,
};
//HTMLImageElement
export const defaultTheme: TDefaultTheme = {
  textDecorationColor: colors,
  colorInterpolation: colors,
  textEmphasisColor: colors,
  placeHolderColor: colors,
  backgroundColor: colors,
  colorRendering: colors,
  textFillColor: colors,
  borderColor: colors,
  linearColor: colors,
  background: colors,
  fontColor: colors,
  color: colors,
  bg: colors,
  scrollbarColor: {
    ...commonProps,
    ...colors,
  },
  paddingBottom: sizeProps,
  marginBottom: sizeProps,
  paddingRight: sizeProps,
  marginRight: sizeProps,
  paddingLeft: sizeProps,
  paddingTop: sizeProps,
  marginLeft: sizeProps,
  marginTop: sizeProps,
  maxHeight: sizeProps,
  minHeight: sizeProps,
  maxWidth: sizeProps,
  minWidth: sizeProps,
  padding: sizeProps,
  bottom: sizeProps,
  margin: sizeProps,
  right: sizeProps,
  minW: sizeProps,
  minH: sizeProps,
  maxH: sizeProps,
  maxW: sizeProps,
  left: sizeProps,
  top: sizeProps,
  mx: sizeProps,
  my: sizeProps,
  px: sizeProps,
  py: sizeProps,
  pb: sizeProps,
  pr: sizeProps,
  mb: sizeProps,
  pl: sizeProps,
  mr: sizeProps,
  ml: sizeProps,
  pt: sizeProps,
  mt: sizeProps,
  p: sizeProps,
  m: sizeProps,
  textIndent: {
    ...sizeProps,
    revertLayer: "revert-layer",
  },
  fontSize: {
    ...sizeProps,
    large: "large",
    medium: "medium",
    small: "small",
    smaller: "smaller",
    xLarge: "x-large",
    xSmall: "x-small",
    xxLarge: "xx-large",
    xxSmall: "xx-small",
    xxxLarge: "xxx-large",
    webkitXxxLarge: "-webkit-xxx-large",
  },
  fontWeight: {
    ...sizeProps,
    "100": "100",
    "200": "200",
    "300": "300",
    "400": "400",
    "500": "500",
    "600": "600",
    "700": "700",
    "800": "800",
    "900": "900",
    bold: "bold",
    bolder: "bolder",
    lighter: "lighter",
    normal: "normal",
  },
  borderRadius: {
    ...commonProps,
    ...sizes,
  },
  gap: {
    ...commonProps,
    ...sizes,
  },
  boxSizing: {
    ...commonProps,
    borderBox: "border-box",
    contentBox: "content-box",
  },
  scrollbarWidth: {
    ...commonProps,
    auto: "auto",
    thin: "thin",
    none: "none",
    revertLayer: "revert-layer",
  },
  objectFit: {
    ...commonProps,
    none: "none",
    contain: "contain",
    cover: "cover",
    fill: "fill",
    scaleDown: "scale-down",
  },
  position: {
    ...commonProps,
    absolute: "absolute",
    fixed: "fixed",
    relative: "relative",
    static: "static",
    sticky: "sticky",
  },
  flexDirection: {
    ...commonProps,
    row: "row",
    rowReverse: "row-reverse",
    column: "column",
    columnReverse: "column-reverse",
  },
  width: {
    ...commonProps,
    fitContent: "fit-content",
    maxContent: "max-content",
    minContent: "min-content",
    webkitFillAvailable: "-webkit-fill-available",
    mozAvailable: "-moz-available",
    optimizedWidth: `-moz-available;width: -webkit-fill-available`,
    ...sizes,
  },
  height: {
    ...commonProps,
    fitContent: "fit-content",
    maxContent: "max-content",
    minContent: "min-content",
    webkitFillAvailable: "-webkit-fill-available",
    mozAvailable: "-moz-available",
    optimizedHeight: `-moz-available;height: -webkit-fill-available`,
    ...sizes,
  },
  display: {
    ...commonProps,
    block: "block",
    contents: "contents",
    flex: "flex",
    flowRoot: "flow-root",
    grid: "grid",
    inline: "inline",
    inlineBlock: "inline-block",
    inlineFlex: "inline-flex",
    inlineGrid: "inline-grid",
    inlineTable: "inline-table",
    listItem: "list-item",
    none: "none",
    table: "table",
    tableCaption: "table-caption",
    tableCell: "table-cell",
    tableColumn: "table-column",
    tableColumnGroup: "table-column-group",
    tableFooterGroup: "table-footer-group",
    tableHeaderGroup: "table-header-group",
    tableRow: "table-row",
    tableRowGroup: "table-row-group",
    webkitBox: "-webkit-box",
    webkitInlineBox: "-webkit-inline-box",
  },
  textAlign: {
    ...commonProps,
    center: "center",
    end: "end",
    justify: "justify",
    left: "left",
    right: "right",
    start: "start",
    webkitAuto: "-webkit-auto",
    webkitCenter: "-webkit-center",
    webkitLeft: "-webkit-left",
    webkitMatchParent: "-webkit-match-parent",
    webkitRight: "-webkit-right",
  },
  flexShrink: {
    ...commonProps,
    revertLayer: "revert-layer",
  },
  zIndex: {
    ...commonProps,
    auto: "auto",
    ...Numbers,
  },
  fontStyle: {
    ...commonProps,
    italic: "italic",
    normal: "normal",
    oblique: "oblique",
  },
  alignContent: {
    ...commonProps,
    baseline: "baseline",
    center: "center",
    end: "end",
    flexEnd: "flex-end",
    flexStart: "flex-start",
    normal: "normal",
    spaceAround: "space-around",
    spaceBetween: "space-between",
    spaceEvenly: "space-evenly",
    start: "start",
    stretch: "stretch",
  },
  alignItems: {
    ...commonProps,
    baseline: "baseline",
    center: "center",
    end: "end",
    flexEnd: "flex-end",
    flexStart: "flex-start",
    normal: "normal",
    selfEnd: "self-end",
    selfStart: "self-start",
    start: "start",
    stretch: "stretch",
  },
  overflowY: {
    ...commonProps,
    auto: "auto",
    clip: "clip",
    hidden: "hidden",
    revertLayer: "revertLayer",
    scroll: "scroll",
    visible: "visible",
  },
  overflowX: {
    ...commonProps,
    auto: "auto",
    clip: "clip",
    hidden: "hidden",
    revertLayer: "revertLayer",
    scroll: "scroll",
    visible: "visible",
  },
  overflow: {
    ...commonProps,
    auto: "auto",
    clip: "clip",
    hidden: "hidden",
    revertLayer: "revertLayer",
    scroll: "scroll",
    visible: "visible",
  },
  flexWrap: {
    ...commonProps,
    noWrap: "nowrap",
    wrap: "wrap",
    wrapReverse: "wrap-reverse",
  },
  gridTemplateColumns: {
    ...commonProps,
    auto: "auto",
    maxContent: "max-content",
    minContent: "min-content",
    none: "none",
  },
  gridTemplateRows: {
    ...commonProps,
    auto: "auto",
    maxContent: "max-content",
    minContent: "min-content",
    none: "none",
  },
  cursor: {
    ...commonProps,
    alias: "alias",
    allScroll: "all-scroll",
    auto: "auto",
    cell: "cell",
    colResize: "col-resize",
    contextMenu: "context-menu",
    copy: "copy",
    crosshair: "crosshair",
    default: "default",
    eResize: "e-resize",
    ewResize: "ew-resize",
    grab: "grab",
    grabbing: "grabbing",
    help: "help",
    move: "move",
    nResize: "n-resize",
    neResize: "ne-resize",
    neswResize: "nesw-resize",
    noDrop: "no-drop",
    none: "none",
    notAllowed: "not-allowed",
    nsResize: "ns-resize",
    nwResize: "nw-resize",
    nwseResize: "nwse-resize",
    pointer: "pointer",
    progress: "progress",
    rowResize: "row-resize",
    sResize: "s-resize",
    seResize: "se-resize",
    swResize: "sw-resize",
    text: "text",
    verticalText: "vertical-text",
    wResize: "w-resize",
    wait: "wait",
    zoomIn: "zoom-in",
    zoomOut: "zoom-out",
    webkitGrab: "-webkit-grab",
    webkitGrabbing: "-webkit-grabbing",
    webkitZoomIn: "-webkit-zoom-in",
    webkitZoomOut: "-webkit-zoom-out",
  },
  alignSelf: {
    ...commonProps,
    auto: "auto",
    baseline: "baseline",
    center: "center",
    end: "end",
    flexEnd: "flex-end",
    flexStart: "flex-start",
    normal: "normal",
    selfEnd: "self-end",
    selfStart: "self-start",
    start: "start",
    stretch: "stretch",
  },
  textWrap: {
    ...commonProps,
    balance: "balance",
    noWrap: "nowrap",
    pretty: "pretty",
    wrap: "wrap",
  },
  justifyContent: {
    ...commonProps,
    center: "center",
    end: "end",
    flexEnd: "flex-end",
    flexStart: "flex-start",
    left: "left",
    normal: "normal",
    right: "right",
    spaceAround: "space-around",
    spaceBetween: "space-between",
    spaceEvenly: "space-evenly",
    start: "start",
    stretch: "stretch",
  },
  textTransform: {
    ...commonProps,
    capitalize: "capitalize",
    lowercase: "lowercase",
    mathAuto: "math-auto",
    none: "none",
    upset: "unset",
    uppercase: "uppercase",
  },
  objectPosition: {
    ...commonProps,
    bottom: "bottom",
    center: "center",
    left: "left",
    right: "right",
    top: "top",
  },
  textDecorationStyle: {
    ...commonProps,
    solid: "solid",
    double: "double",
    dotted: "dotted",
    dashed: "dashed",
    wavy: "wavy",
  },
  textUnderlineOffset: {
    ...commonProps,
    auto: "auto",
  },
  textEmphasis: {
    ...commonProps,
    none: "none",
    accent: "accent",
    dot: "dot",
    circle: "circle",
    disc: "disc",
  },
  borderImageRepeat: {
    ...commonProps,
    stretch: "stretch",
    repeat: "repeat",
    round: "round",
    space: "space",
  },
  borderImageWidth: {
    ...commonProps,
    auto: "auto",
  },
  borderBlock: {
    ...commonProps,
    start: "start",
    end: "end",
  },
  textDecorationLine: {
    ...commonProps,
    lineThrough: "line-through",
    overline: "overline",
    underline: "underline",
    blink: "blink",
  },
  transformStyle: {
    ...commonProps,
    flat: "flat",
    preserve3d: "preserve-3d",
  },
  justifyItems: {
    ...commonProps,
    auto: "auto",
    baseline: "baseline",
    center: "center",
    end: "end",
    start: "start",
    stretch: "stretch",
  },
  whiteSpace: {
    ...commonProps,
    breakSpaces: "break-spaces",
    normal: "normal",
    nowrap: "nowrap",
    pre: "pre",
    preLine: "pre-line",
    preWrap: "pre-wrap",
    revertLayer: "revert-layer",
    mozPreSpace: "-moz-pre-space",
  },
  lineHeight: {
    ...commonProps,
    normal: "normal",
    revertLayer: "revert-layer",
    mozBlockHeight: "-moz-block-height",
    ...sizes,
  },
  textRendering: {
    ...commonProps,
    auto: "auto",
    geometricPrecision: "geometricprecision",
    optimizeLegibility: "optimizelegibility",
    optimizeSpeed: "optimizespeed",
    revertLayer: "revert-layer",
  },
  textDecoration: {
    auto: "auto",
    blink: "blink",
    dashed: "dashed",
    double: "double",
    lineThrough: "line-through",
    none: "none",
    overline: "overline",
    solid: "solid",
    underline: "underline",
    wavy: "wavy",
    revertLayer: "revert-layer",
    ...commonProps,
  },
  textOverflow: {
    ellipsis: "ellipsis",
    clip: "clip",
    revertLayer: "revert-layer",
    ...commonProps,
  },
  pointerEvents: {
    ...commonProps,
    all: "all",
    auto: "auto",
    boundingBox: "bounding-box",
    fill: "fill",
    none: "none",
    painted: "painted",
    stroke: "stroke",
    visible: "visible",
    visibleFill: "visiblefill",
    visiblePainted: "visiblepainted",
    visibleStroke: "visiblestroke",
  },
  userSelect: {
    all: "all",
    auto: "auto",
    none: "none",
    text: "text",
    contain: "contain",
    revertLayer: "revert-layer",
    ...commonProps,
  },
  borderImageOutset: commonProps,
  borderImageSlice: commonProps,
  borderImageSource: commonProps,
  transition: commonProps,
  opacity: commonProps,
  backgroundClipText: commonProps,
  boxShadow: commonProps,
  backgroundTranslucent: commonProps,
  filter: commonProps,
  bTopRadius: commonProps,
  bBottomRadius: commonProps,
  bRadius: commonProps,
  bLeftRadius: commonProps,
  bRightRadius: commonProps,
  bRadiusTop: commonProps,
  bRadiusBottom: commonProps,
  bRadiusLeft: commonProps,
  bRadiusRight: commonProps,
  bRadiusTopLeft: commonProps,
  bRadiusTopRight: commonProps,
  bRadiusBottomLeft: commonProps,
  bRadiusBottomRight: commonProps,
  flexGrow: commonProps,
  gridColumnGap: commonProps,
  gridRowGap: commonProps,
  gridGap: commonProps,
  gridAutoFlow: commonProps,
  gridAutoColumns: commonProps,
  gridAutoRows: commonProps,
  gridColumnStart: commonProps,
  gridColumnEnd: commonProps,
  gridRowStart: commonProps,
  gridRowEnd: commonProps,
  gridRow: commonProps,
  gridColumn: commonProps,
  gridColumnStartEnd: commonProps,
  gridRowStartEnd: commonProps,
  justifySelf: commonProps,
  placeItems: commonProps,
  placeContent: commonProps,
  placeSelf: commonProps,
  userDrag: commonProps,
  userResize: commonProps,
  transitionProperty: commonProps,
  transitionDuration: commonProps,
  transitionTimingFunction: commonProps,
  transitionDelay: commonProps,
  animation: commonProps,
  transform: commonProps,
  transformOrigin: commonProps,
  perspective: commonProps,
  perspectiveOrigin: commonProps,
  backfaceVisibility: commonProps,
  willChange: commonProps,
  letterSpacing: commonProps,
  wordSpacing: commonProps,
  columnCount: commonProps,
  columnGap: commonProps,
  columnRule: commonProps,
  columnWidth: commonProps,
  scrollSnapType: commonProps,
  scrollBehavior: commonProps,
  scrollSnapAlign: commonProps,
  animationDelay: commonProps,
  animationDirection: commonProps,
  animationDuration: commonProps,
  animationFillMode: commonProps,
  animationIterationCount: commonProps,
  animationName: commonProps,
  animationPlayState: commonProps,
  animationTimingFunction: commonProps,
  boxShadowInset: commonProps,
  userFocus: commonProps,
  userSelectText: commonProps,
  userSelectNone: commonProps,
  userSelectAll: commonProps,
  userSelectAuto: commonProps,
  mixBlendMode: commonProps,
  clipPath: commonProps,
  backdropFilter: commonProps,
  backdropBlur: commonProps,
  backdropBrightness: commonProps,
  backdropContrast: commonProps,
  backdropGrayscale: commonProps,
  backdropHueRotate: commonProps,
  backdropInvert: commonProps,
  backdropOpacity: commonProps,
  backdropSaturate: commonProps,
  backdropSepia: commonProps,
  backdropDropShadow: commonProps,
  borderImage: commonProps,
  textEmphasisStyle: commonProps,
  textEmphasisPosition: commonProps,
  scrollSnapPointsX: commonProps,
  scrollSnapPointsY: commonProps,
  columnSpan: commonProps,
  hyphens: commonProps,
  textAlignLast: commonProps,
  textJustify: commonProps,
  fontVariant: commonProps,
  fontFeatureSettings: commonProps,
  wordBreak: commonProps,
  wordWrap: commonProps,
  overscrollBehavior: commonProps,
  overscrollBehaviorX: commonProps,
  overscrollBehaviorY: commonProps,
  clipRule: commonProps,
  fillRule: commonProps,
  isolation: commonProps,
  resize: commonProps,
  shapeOutside: commonProps,
  listStyleType: commonProps,
  listStylePosition: commonProps,
  listStyleImage: commonProps,
  userZoom: commonProps,
  maxLines: commonProps,
  textDecorationSkipInk: commonProps,
  transitionTiming: commonProps,
  transitionDurationTiming: commonProps,
  scrollMargin: commonProps,
  scrollMarginBlock: commonProps,
  scrollMarginBlockStart: commonProps,
  scrollMarginBlockEnd: commonProps,
  scrollMarginInline: commonProps,
  scrollMarginInlineStart: commonProps,
  scrollMarginInlineEnd: commonProps,
  maskImage: commonProps,
  maskSize: commonProps,
  maskRepeat: commonProps,
  maskPosition: commonProps,
  maskClip: commonProps,
  maskOrigin: commonProps,
  maskComposite: commonProps,
  maskType: commonProps,
  maskBorder: commonProps,
  maskBorderOutset: commonProps,
  maskBorderRepeat: commonProps,
  maskBorderSlice: commonProps,
  maskBorderSource: commonProps,
  maskBorderWidth: commonProps,
  maskBorderRepeatX: commonProps,
  maskBorderRepeatY: commonProps,
  scrollSnapStop: commonProps,
  scrollSnapAlignY: commonProps,
  scrollSnapAlignX: commonProps,
  scrollSnapStopX: commonProps,
  scrollSnapStopY: commonProps,
  boxShadowX: commonProps,
  boxShadowY: commonProps,
  backdropBlendMode: commonProps,
  backdropDropShadowX: commonProps,
  backdropDropShadowY: commonProps,
  backdropDropShadowBlur: commonProps,
  backdropDropShadowSpread: commonProps,
  gridAutoRowsMin: commonProps,
  gridAutoRowsMax: commonProps,
  gridAutoColumnsMin: commonProps,
  gridAutoColumnsMax: commonProps,
  gridColumnStartMin: commonProps,
  gridColumnStartMax: commonProps,
  gridColumnEndMin: commonProps,
  gridColumnEndMax: commonProps,
  gridRowStartMin: commonProps,
  gridRowStartMax: commonProps,
  gridRowEndMin: commonProps,
  gridRowEndMax: commonProps,
  shapeMargin: commonProps,
  shapeImageThreshold: commonProps,
  filterBlur: commonProps,
  filterBrightness: commonProps,
  filterContrast: commonProps,
  filterGrayscale: commonProps,
  filterHueRotate: commonProps,
  filterInvert: commonProps,
  filterOpacity: commonProps,
  filterSaturate: commonProps,
  filterSepia: commonProps,
  filterDropShadow: commonProps,
  willChangeProperty: commonProps,
  backgroundClip: commonProps,
  imageRendering: commonProps,
  shapeRendering: commonProps,
  border: commonProps,
  textShadow: commonProps,
};
