export const PseudoElements = {
  mozSelection: "::moz-selection",
  mozPlaceholder: "::moz-placeholder",
  mozFocusInner: "::moz-focus-inner",
  mozFocusOuter: "::moz-focus-outer",
  mozTreeCellText: "::moz-tree-cell-text",
  mozTreeCellTextHover: "::moz-tree-cell-text(hover)",
  mozTreeCellTextSelected: "::moz-tree-cell-text(selected)",
  mozTreeCellTextLoading: "::moz-tree-cell-text(loading)",
  mozTreeCellTextHoverSelected: "::moz-tree-cell-text(hover, selected)",
  mozTreeCellTextHoverLoading: "::moz-tree-cell-text(hover, loading)",
  mozTreeCellTextSelectedLoading: "::moz-tree-cell-text(selected, loading)",
  mozTreeCellTextHoverSelectedLoading:
    "::moz-tree-cell-text(hover, selected, loading)",
  mozTreeRowHover: "::moz-tree-row(hover)",
  mozTreeRowSelected: "::moz-tree-row(selected)",
  mozTreeRowLoading: "::moz-tree-row(loading)",
  mozTreeRowHoverSelected: "::moz-tree-row(hover, selected)",
  mozTreeRowHoverLoading: "::moz-tree-row(hover, loading)",
  mozTreeRowSelectedLoading: "::moz-tree-row(selected, loading)",
  mozTreeRowHoverSelectedLoading: "::moz-tree-row(hover, selected, loading)",
  webkitInputPlaceholder: "::webkit-input-placeholder",
  webkitProgressBar: "::webkit-progress-bar",
  webkitProgressValue: "::webkit-progress-value",
  webkitProgressBarValue: "::webkit-progress-bar-value",
  webkitMeterBar: "::webkit-meter-bar",
  webkitMeterOptimumValue: "::webkit-meter-optimum-value",
  webkitContactsAutoCompleteContainer:
    "::webkit-contacts-auto-complete-container",
  webkitContactsAutoCompleteEntry: "::webkit-contacts-auto-complete-entry",
  webkitContactsAutoCompleteButton: "::webkit-contacts-auto-complete-button",
  webkitContactsAutoCompleteButtonContainer:
    "::webkit-contacts-auto-complete-button-container",
  webkitContactsAutoCompleteSelectedEntry:
    "::webkit-contacts-auto-complete-selected-entry",
  after: "::after",
  before: "::before",
  firstLetter: "::first-letter",
  firstLine: "::first-line",
  selection: "::selection",
  backdrop: "::backdrop",
  placeholder: "::placeholder",
  marker: "::marker",
  spellingError: "::spelling-error",
  grammarError: "::grammar-error",
  cue: "::cue",
  cueRegion: "::cue-region",
};
