export const alignContent = {
  baseline: "baseline",
  center: "center",
  end: "end",
  flexEnd: "flex-end",
  flexStart: "flex-start",
  inherit: "inherit",
  initial: "initial",
  normal: "normal",
  revert: "revert",
  spaceAround: "space-around",
  spaceBetween: "space-between",
  spaceEvenly: "space-evenly",
  start: "start",
  stretch: "stretch",
  unset: "unset",
};
