export const AtRules = {
  charset: "@charset",
  import: "@import",
  namespace: "@namespace",
  keyframes: "@keyframes",
  viewport: "@viewport",
  counterStyle: "@counter-style",
  fontFace: "@font-face",
  supports: "@supports",
  document: "@document",
  page: "@page",
  media: "@media",
  fontFeatureValues: "@font-feature-values",
  swash: "@swash",
  ornaments: "@ornaments",
  annotation: "@annotation",
  stylistic: "@stylistic",
  styleset: "@styleset",
  characterVariant: "@character-variant",
};
