export const cssReset = `html{
line-height:1.15;/*1*/
-webkit-text-size-adjust:100%;/*2*/
height:100%;
margin:0;
padding:0;
}
body{
height:100%;
margin:0;
padding:0;
}
main{
display:block;
}
h1{
font-size:2em;
margin:0;
}
p{
margin:0;
}
hr{
box-sizing:content-box;/*1*/
height:0;/*1*/
overflow:visible;/*2*/
}
pre{
font-family:monospace,monospace;/*1*/
font-size:1em;/*2*/
}
a{
background-color:transparent;
}
abbr[title]{
border-bottom:none;/*1*/
text-decoration:underline;/*2*/
text-decoration:underlinedotted;/*2*/
}
b{
font-weight:bolder;
}
strong{
font-weight:bolder;
}
code{
font-family:monospace,monospace;/*1*/
font-size:1em;/*2*/
}
kbd{
font-family:monospace,monospace;/*1*/
font-size:1em;/*2*/
}
samp{
font-family:monospace,monospace;/*1*/
font-size:1em;/*2*/
}
small{
font-size:80%;
}
sub{
font-size:75%;
line-height:0;
position:relative;
vertical-align:baseline;
}
sup{
font-size:75%;
line-height:0;
position:relative;
vertical-align:baseline;
}
sub{
bottom:-0.25em;
}
sup{
top:-0.5em;
}
img{
border-style:none;
}
button{
font-family:inherit;/*1*/
font-size:100%;/*1*/
line-height:1.15;/*1*/
margin:0;/*2*/
}
input{
font-family:inherit;/*1*/
font-size:100%;/*1*/
line-height:1.15;/*1*/
margin:0;/*2*/
}
optgroup{
font-family:inherit;/*1*/
font-size:100%;/*1*/
line-height:1.15;/*1*/
margin:0;/*2*/
}
select{
font-family:inherit;/*1*/
font-size:100%;/*1*/
line-height:1.15;/*1*/
margin:0;/*2*/
}
textarea{
font-family:inherit;/*1*/
font-size:100%;/*1*/
line-height:1.15;/*1*/
margin:0;/*2*/
}
button{
/*1*/
overflow:visible;
}
input{
/*1*/
overflow:visible;
}
button{
/*1*/
text-transform:none;
}
select{
/*1*/
text-transform:none;
}
button{
-webkit-appearance:button;
}
[type="button"]{
-webkit-appearance:button;
}
[type="reset"]{
-webkit-appearance:button;
}
[type="submit"]{
-webkit-appearance:button;
}
button::-moz-focus-inner{
border-style:none;
padding:0;
}
[type="button"]::-moz-focus-inner{
border-style:none;
padding:0;
}
[type="reset"]::-moz-focus-inner{
border-style:none;
padding:0;
}
[type="submit"]::-moz-focus-inner{
border-style:none;
padding:0;
}
button:-moz-focusring{
outline:1pxdottedButtonText;
}
[type="button"]:-moz-focusring{
outline:1pxdottedButtonText;
}
[type="reset"]:-moz-focusring{
outline:1pxdottedButtonText;
}
[type="submit"]:-moz-focusring{
outline:1pxdottedButtonText;
}
fieldset{
padding:0.35em0.75em0.625em;
}
legend{
box-sizing:border-box;/*1*/
color:inherit;/*2*/
display:table;/*1*/
max-width:100%;/*1*/
padding:0;/*3*/
white-space:normal;/*1*/
}
progress{
vertical-align:baseline;
}
textarea{
overflow:auto;
}
[type="checkbox"]{
box-sizing:border-box;/*1*/
padding:0;/*2*/
}
[type="radio"]{
box-sizing:border-box;/*1*/
padding:0;/*2*/
}
[type="number"]::-webkit-inner-spin-button{
height:auto;
}
[type="number"]::-webkit-outer-spin-button{
height:auto;
}
[type="search"]{
-webkit-appearance:textfield;/*1*/
outline-offset:-2px;/*2*/
}
[type="search"]::-webkit-search-decoration{
-webkit-appearance:none;
}
::-webkit-file-upload-button{
-webkit-appearance:button;/*1*/
font:inherit;/*2*/
}
details{
display:block;
}
summary{
display:list-item;
}
template{
display:none;
}
[hidden]{
display:none;
}`;
