name: "Devops"

on:
  push:
    branches: ["main", "Main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "19 8 * * 4"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  MSDO:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            5.0.x
            6.0.x
      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v1.6.0
        id: msdo
      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
  publish:
    name: Publish Workflow
    runs-on: ubuntu-latest
    needs: MSDO
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint and Build Packages
        run: pnpm run lint && pnpm run build:packages

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Setup Git User
        shell: bash
        run: |
          git config --global user.email "nahuel.rosas@mi.unc.edu.ar"
          git config --global user.name "Nahuel Rosas"

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "ci(changesets): version packages"
          setupGitUser: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git checkout main
        if: steps.changesets.outputs.published != 'true'
        run: git checkout main

      - name: Create version dev
        if: steps.changesets.outputs.published != 'true'
        run: pnpm version:dev

      - name: Create release Pull Request or publish to NPM
        if: steps.changesets.outputs.published != 'true'
        id: changesets-dev
        uses: changesets/action@v1
        with:
          publish: pnpm release:dev
          commit: "ci(changesets): version packages"
          setupGitUser: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
